apiVersion: v1
kind: ConfigMap
metadata:
  namespace: NAMESPACE_PLACEHOLDER
  name: SERVICENAME_PLACEHOLDER-configmap-blue
data:
  aws_region: "us-east-1"
  cloudwatch_logs: "LOG_GROUP_PLACEHOLDER"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: NAMESPACE_PLACEHOLDER
  name: SERVICENAME_PLACEHOLDER-backend-blue
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: SERVICENAME_PLACEHOLDER-backend-blue
  replicas: 2
  template:
    metadata:
      labels:
        app.kubernetes.io/name: SERVICENAME_PLACEHOLDER-backend-blue
    spec:
      serviceAccountName: CLUSTER_NAME_PLACEHOLDER-sa-SERVICENAME_PLACEHOLDER
      containers:
      ## Change the image
      - image: ECR_REPO_PLACEHOLDER
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        imagePullPolicy: Always
        name: SERVICENAME_PLACEHOLDER-backend-blue
        env:
          - name: AWS_REGION
            valueFrom:
              configMapKeyRef:
                name: SERVICENAME_PLACEHOLDER-configmap-blue
                key: aws_region
          - name: LOG_GROUP_NAME
            valueFrom:
              configMapKeyRef:
                name: SERVICENAME_PLACEHOLDER-configmap-blue
                key: cloudwatch_logs
        ports:
        - containerPort: 80
#        securityContext:
#          allowPrivilegeEscalation: false
#          runAsNonRoot: true
